baseURL: "https://aut.fxz.es/"
locale: "zh-cn"
title: "Auto-Cui"
theme: "paper"

params:
  color: "linen"
  name: "Auto-Cui"
  bio: "让工具成为工具，让你成为你"
  avatar: "https://aut.fxz.es/images/avatar.png"

menu:
  main:
    - identifier: "home"
      name: "首页"
      url: "/"
      weight: 1
    - identifier: "software"
      name: "软件"
      url: "/categories/软件/"
      weight: 2
    - identifier: "essay"
      name: "随笔"
      url: "/categories/随笔/"
      weight: 3
    - identifier: "tech"
      name: "技术"
      url: "/categories/技术/"
      weight: 4     